#!/bin/bash

# Left Stats Bar
## System
## Processor
## Memory and Disks
## Network Info
conky -d -c /home/vedang/Source/scripts/conkyrc-stats-left &

# Right Stats Bar
## Time
## Todo
## Music
## Twitter
conky -d -c /home/vedang/Source/scripts/conkyrc-stats-right &

exit
